### ISSUE TITLE
Top half (include search tab)

### ISSUE THREAD

**Issue by nantapong44** [encX/bangkok-transit-planner#7]

**Comment by nantapong44** [comment]
![image](https://user-images.githubusercontent.com/34004759/88683384-edacc100-d11d-11ea-9fb2-de7242771a86.png)

**Comment by nantapong44** [comment]
For mobile

![image](https://user-images.githubusercontent.com/34004759/88683506-15038e00-d11e-11ea-9af6-ca40d7ca2761.png)

**Comment by encX** [comment]
### Search boxes
- Desktop: searchable dropdown
- Mobile: search result page with search field
