### ISSUE TITLE
Bottom half 

### ISSUE THREAD

**Issue by nantapong44** [encX/bangkok-transit-planner#8]

**Comment by nantapong44** [comment]
![image](https://user-images.githubusercontent.com/34004759/88683445-0321eb00-d11e-11ea-8c47-30a78fd33f8a.png)

**Comment by encX** [comment]
![image](https://user-images.githubusercontent.com/5965883/90339345-5cdd4d00-e01a-11ea-9c6b-a35b3019c5fa.jpeg)

**Comment by encX** [comment]
![image](https://user-images.githubusercontent.com/5965883/90339352-69fa3c00-e01a-11ea-8bb3-ba295f436db0.jpeg)
